nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Utilise la variable d'environnement
        allow_headers: ['*'] # Accepte tous les en-têtes
        allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
    paths:
        '^/api/': # Applique uniquement sur les routes /api/
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS']
