services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:443
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      #DATABASE_URL: "postgresql://postgres.jwxdrchoqzshdgdcwnxf:d4bgXT0k6DKLrQpq@aws-0-eu-west-3.pooler.supabase.com:5432/postgres"
      #DATABASE_URL: "postgresql://postgres.uecmwridhjawxqkyyisk:QJprqM4v6wdREmd8@aws-0-eu-west-3.pooler.supabase.com:6543/postgres"
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-mypgdbpass}@postgres:5432/${POSTGRES_DB:-postgres}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      #DATABASE_URL: "postgresql://postgres.postgres:mypgdbpass@postgres:5432/postgres?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}"
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./app:/app
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  vite:
    image: node:20
    container_name: vite_container
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app  # Montera le répertoire de votre projet dans le conteneur
    ports:
      - "5173:5173"  # Expose le port de Vite
    environment:
      - VITE_SERVER_HOST=0.0.0.0  # Permet d'écouter toutes les connexions
    depends_on:
      - php  # Assure que Symfony démarre avant Vite
    networks:
      - symfony-vite-network

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypgdbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypgadminpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  caddy_data:
  caddy_config:
###> symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  postgres_data:
  pgadmin_data:
###< doctrine/doctrine-bundle ###
###< symfony/mercure-bundle ###

networks:
  symfony-vite-network:
    driver: bridge
